img1=imread('quickbirdsub.tif');
img2=imread('livingroom.tif');
img2_hist=imhist(img2);
img_match=histeq(img1,img2_hist);%Ö±·½Í¼Æ¥Åä
figure
subplot(1,2,1),imshow(img1);title('Ô­Í¼Ïñ');
subplot(1,2,2),imshow(img2);title('Æ¥ÅäÍ¼Ïñ');
figure
imshow(img_match);title('Æ¥ÅäÖ®ºóÍ¼Ïñ');